[package]
name = "fe2io-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.12", features = ["blocking" ] }
tungstenite = "0.26.2"
rodio = { version = "0.20.1", default-features = false, features = ["symphonia-aac", "symphonia-alac", "minimp3", "hound"] }
clap = { version = "4.5.30", features = ["derive"] }
log = "0.4.26"
env_logger = "0.11.6"
thiserror = "2.0.11"
miniserde = "0.1.41"

[profile.release]
opt-level = 'z'
panic = 'abort'
strip = true
