[package]
name = "fe2io-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.139"
reqwest = { version = "0.12.12", features = ["blocking" ] }
tungstenite = "0.26.2"
json = "0.12.4"
rodio = "0.20.1"
clap = { version = "4.5.30", features = ["derive"] }
anyhow = "1.0.96"
