[package]
name = "fe2io-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.12", features = ["blocking" ] }
rodio = { version = "0.20.1", default-features = false, features = ["symphonia-aac", "symphonia-alac", "minimp3", "hound"] }
clap = { version = "4.5.30", features = ["derive"] }
log = "0.4.26"
env_logger = "0.11.6"
thiserror = "2.0.11"
miniserde = "0.1.41"
tokio = { version = "1.43.0", features = ["rt-multi-thread", "macros"] }
async-tungstenite = { version = "0.29.1", features = ["tokio-runtime"] }
futures = "0.3.31"

[profile.release]
opt-level = 'z'
panic = 'abort'
strip = true
